[package]
name = "fixture"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "fixture"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

fixture_integrity = { workspace = true } 
