name: Integration Test

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.20.1/install

      - name: Set up cachix
        uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - name: Build fixture
        run: nix develop -c $SHELL -c "cd fixture && npm install && npm run build:happ"

      - name: Prepare environment
        run: nix develop -c $SHELL -c "python -m venv .venv && source .venv/bin/activate && poetry install --no-root"

      - name: Check formatting
        run: nix develop -c $SHELL -c "source .venv/bin/activate && poetry run ruff format --diff"

      - name: Lint
        run: nix develop -c $SHELL -c "source .venv/bin/activate && poetry run ruff check"

      - name: Run tests
        run: nix develop -c $SHELL -c "source .venv/bin/activate && poetry run pytest"
